config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  patch '/profile', to: 'pages#update_profile'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_error'
  get '/422', to: 'errors#unacceptable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :itineraries do
    member do
      post "reorder", to: "locations#change_order"
    end
    resources :locations
    resources :reviews, only: [:new, :create]
    member do
      post 'clone', to: "itineraries#clone"
    end
  end

end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  has_many :reviews

  has_many :itinerary_locations
  has_many :locations, through: :itinerary_locations

  has_one_attached :photo

  # include PgSearch::Model
  # multisearchable against: [:name]

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name ],
    associated_against: {
      locations: [ :name, :address ]
    },
    using: {
      tsearch: { prefix: true }
    }

  def markers_method
      self.locations.map do |location|
        {
          "lat" => location.latitude,
          "lng" => location.longitude
        }
      end
  end


  def self.tagged_with(word)
    locations = Location.tagged_with(word)
    return [] if locations.empty?

    locations.map do |loc|
      loc.itineraries
    end.uniq.flatten

  end

  def clone_with_locations(user)
    attr = self.attributes
    attr = attr.except("id", "user_id", "created_at", "updated_at")
    new_itinerary = Itinerary.new(attr)
    new_itinerary.user = user
    new_itinerary.name = "**COPY OF " + new_itinerary.name + "**"
    new_itinerary.photo = self.photo.blob
    new_itinerary.save


    locs = self.locations.map do |loc|
      loc_attr = loc.attributes


      loc_attr = loc_attr.except("id", "created_at", "updated_at")
      new_location = Location.new(loc_attr)
      loc.tag_list.each do |tag|
        new_location.tag_list.add(tag)
      end
      new_location.save

      if loc.photos.attached?
        loc.photos.each do |ph|
          new_location.photos.attach(ph.blob)
        end
      end

      drag_order = itinerary_locations.find_by(location: loc).drag_order

      ItineraryLocation.create(location: new_location, itinerary: new_itinerary, drag_order: drag_order)
    end

    new_itinerary
  end

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :find_itinerary, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?

      @itineraries_global = policy_scope(Itinerary).global_search(params[:query])

      @itineraries_by_tag = policy_scope(Itinerary).tagged_with(params[:query])

      @itineraries = (@itineraries_global + @itineraries_by_tag).uniq
      # sql_query = " \
      #   itineraries.name ILIKE :query \
      #   OR locations.name ILIKE :query \
      #   OR locations.address ILIKE :query \
      # "
      # @itineraries = policy_scope(Itinerary).joins(:locations).where(sql_query, query: "%#{params[:query]}%").uniq
    else
      @itineraries = policy_scope(Itinerary)
    end
  end

  def show
    @skip_footer = true

    @locations = @itinerary.locations.order("itinerary_locations.drag_order ASC")

    @location = Location.new

    @markers = @locations.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { location: location })
      }
    end

    @review = Review.new
    @reviews = @itinerary.reviews
  end

  def new
    @itinerary = Itinerary.new
    authorize @itinerary
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)
    authorize @itinerary
    @itinerary.duration = 0
    @itinerary.user = current_user

    if @itinerary.save
      redirect_to @itinerary
    else
      render :new
    end
  end

  def edit; end

  def update
    @itinerary.update(itinerary_params)

    redirect_to @itinerary
  end

  def destroy
    @itinerary.destroy

    redirect_to itineraries_path
  end

  def clone
    @itinerary = Itinerary.find(params[:id])
    authorize @itinerary
    @new_itinerary = @itinerary.clone_with_locations(current_user)
    redirect_to edit_itinerary_path(@new_itinerary), notice: "Itinerary Cloned!"
  end

  private

  def itinerary_params
    params.require(:itinerary).permit(:name, :description, :photo)
  end

  def find_itinerary
    @itinerary = Itinerary.find(params[:id])
    authorize @itinerary
  end
end

app/views/itineraries/_horizontal_navbar.html.erb
<div class="icon-bar pb-1">
  <!-- <div class="fill-color">
    <a class="" href="#">
      <%= link_to itineraries_path do %>
       <h3>Go Back</h3>
        <i class="fas fa-arrow-circle-left horiz-icon"></i>
      <% end %>
    </a>
  </div> -->

  <div class="fill-color">
    <a href="#">
      <% if @itinerary.locations.exists? %>
        <%=link_to googlemap(@itinerary), target: "_blank", class: 'btn-google-maps' do %>
          <h3>Google Maps</h3>
          <i class="fab fa-google horiz-icon"></i>
        <% end %>
      <% end %>
    </a>
  </div>

  <div class="fill-color">
    <a href="#" id="myBtn-x">
      <h3>Photos</h3>
      <i class="fas fa-camera horiz-icon"></i>
    </a>
  </div>

  <div class="fill-color hide-itinerary">
    <a href="#" >
      <h3>Share</h3>
      <i class="fas fa-share horiz-icon"></i>
    </a>

  </div>

  <div class="fill-color">
    <a href="#">
      <%= link_to clone_itinerary_path(@itinerary), method: :post do %>
        <h3>Copy</h3>
        <i class="far fa-clone horiz-icon"></i>
      <% end %>
    </a>
  </div>

  <div class="fill-color">
    <a href="#">
      <% if policy(@itinerary).destroy? %>
        <%= link_to @itinerary, method: :delete, data: { confirm: 'Are you sure?' } do%>
          <h3>Delete</h3>
          <i class="far fa-trash-alt horiz-icon"></i>
        <% end %>
      <% end %>
    </a>
  </div>
</div>

app/views/itineraries/_image_carousel.html.erb
<%if @locations.exists?%>
<div class="carousel-photo">
  <div id="carouselExampleControls" class="carousel slide " data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active carousel-item-height">
        <h1 style="color: rgba(1, 80, 89, 1); font-size:20px; font-weight:bold; text-align:center;"><%= @locations.first.name %></h1>
        <h3 style="font-size: 16px; text-align:center;"> <%= @locations.first.description %></h3>
        <% if @locations.first.photos.attached? %>
          <%= cl_image_tag @locations.first.photos.first.key,  :crop=>"fill", class: "d-block w-100", alt: 'First Slide' %>
        <% else %>
          <%= cl_image_tag "thzwKfbAd91nNz2xZx7sGt3p", :crop=>"fill", class: "d-block w-100", alt: 'First Slide' %>
        <% end %>
      </div>

      <% @locations.drop(1).each do |location| %>
        <div class="carousel-item carousel-item-height">
         <h1 style="color: rgba(1, 80, 89, 1); font-size:20px; font-weight:bold; text-align:center;"><%= location.name %></h1>
         <h3 style="font-size: 16px; text-align:center;"><%= location.description %> </h3>
          <% if location.photos.attached? %>
            <%= cl_image_tag location.photos.first.key,  :crop=>"fill", class: "d-block w-100" %>
          <% else %>
            <%= cl_image_tag "thzwKfbAd91nNz2xZx7sGt3p", :crop=>"fill", class: "d-block w-100" %>
          <% end %>
        </div>
        <% end %>
      </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<% end %>

app/views/itineraries/_info_window.html.erb
<h2><%= location.name.capitalize %></h2>
<p><%= location.address %></p>

app/views/itineraries/_itinerary_details.html.erb
  <% if @itinerary.photo.attached? %>
<div class="trip-overview trip-overview-image" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path @itinerary.photo.key, crop: :scale %>')">
  <% else %>
<div class="trip-overview">
  <% end %>
  <h1>Trip Overview</h1>
  <p class="itinerary-desription"><%= @itinerary.description %></p>

  <div class='align-items-end'>
    <div class="d-flex align-items-center">
      <i class="fas fa-map-marker-alt itinerary-icon"></i>
      <h2 class="detail-header">Total Stops: <%= @itinerary.locations.count %> </h2>
    </div>

    <div class="d-flex align-items-center ">
      <i class="far fa-clock itinerary-icon"></i>
      <h2 class="detail-header" id="trip-duration" data-duration="<%= itinerary.duration.to_json %>">Location Time: <%= duration(itinerary.duration) %>  </h2>
    </div>

    <div class="d-flex align-items-center align-self-end">
      <i class="fas fa-tag itinerary-icon"></i>
      <ul class="details-itinerary detail-header">
        <li style="font-weight: bold">Trip Type: </li>
        <% @itinerary.locations[0..2].each do |location| %>
        <li style="font-weight: bold"><%=location.tag_list.first%></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/itineraries/_location_form.html.erb
<%= simple_form_for [itinerary, location], html: { autocomplete: "off" } do |f| %>
  <div class="itinerary-large-fields the-location">
    <%= f.input :address, label: false, placeholder: "Search for destinations"%>
  </div>
  <div class="itinerary-large-fields">
    <%= f.input :name, label: false, placeholder: "Customize the name of your location" %>
  </div>
  <div class="form-short-box">
    <div class=" d-flex align-items-center form-tag-icon">
      <i class="fas fa-tag icon-form"></i>
      <%= f.input :tag_list, label: false, placeholder: "Add Interest Tags", class: 'location-fields' %>
      </div>

    <div class="d-flex align-items-center text-sm">
      <i class="far fa-clock icon-form p-0 ml-2 "></i>
      <%= f.input :duration, label: false, placeholder: "Mins @Destination", class: 'text-sm' %>

    </div>
    <label class="mr-2" style="cursor: pointer; margin:0px; font-size: 18px; color: rgb(108,117,125)"> 📸Add Photo
    <span style="display:none; ">
    <%= f.input :photos, as: :file, input_html: { multiple: true }, label: false%>
    </span>
    </label>
  </div>
  <div class= "d-flex align-items-center">

    <%= f.button :submit, 'Add Location', class: 'btn-location-add location-button' %>
  </div>
<% end %>

app/views/itineraries/_review.html.erb
<div class="review-card">
  <h5><%= review.user.username.capitalize %></h5>
  <p><%= time_ago_in_words(review.created_at) %></p>
  <p><%= stars(review.rating) %></p>
  <p><%= review.description %></p>
</div>

app/views/itineraries/_review_button.html.erb
<% if current_user %>
 <%= rating(itinerary.reviews) %>
<% end %>

app/views/itineraries/_review_form.html.erb
<%= simple_form_for([itinerary, review], remote: true) do |f| %>
  <%= f.input :description %>
  <%= f.input :rating %>
  <%= f.button :submit, 'Add Review', class: 'btn-location-add review-form-btn' %>
<% end %>

app/views/itineraries/_review_rating.html.erb
<div class="review-rating">
  <h5><%= total_rating(itinerary.reviews) %></h5>
</div>

app/views/itineraries/edit.html.erb
<%= render 'form', itinerary: @itinerary %>

app/views/itineraries/map_index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css' rel='stylesheet' />
    <style>
      body {
        margin: 0;
        padding: 0;
      }

      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id='map'></div>
    <script>
      mapboxgl.accessToken = 'pk.eyJ1Ijoic3RldmVzcGlkZXJzIiwiYSI6ImNrN2JqZW43MjAyM3YzcWxjb2VkZG9qNmUifQ.iMQH53oEUdtY8nAbUaAl3w';
      var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v10',
        center: [-122.662323, 45.523751], // starting position
        zoom: 12
      });
      // set the bounds of the map
      var bounds = [[-123.069003, 45.395273], [-122.303707, 45.612333]];
      map.setMaxBounds(bounds);

      // initialize the map canvas to interact with later
      var canvas = map.getCanvasContainer();

      // an arbitrary start will always be the same
      // only the end or destination will change
      var start = [-122.662323, 45.523751];

      // this is where the code for the next step will go
      // create a function to make a directions request
      function getRoute(end) {
        // make a directions request using cycling profile
        // an arbitrary start will always be the same
        // only the end or destination will change
        var start = [-122.662323, 45.523751];
        var url = 'https://api.mapbox.com/directions/v5/mapbox/cycling/' + start[0] + ',' + start[1] + ';' + end[0] + ',' + end[1] + '?steps=true&geometries=geojson&access_token=' + mapboxgl.accessToken;

        // make an XHR request https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
        var req = new XMLHttpRequest();
        req.open('GET', url, true);
        req.onload = function() {
          var json = JSON.parse(req.response);
          var data = json.routes[0];
          var route = data.geometry.coordinates;
          var geojson = {
            type: 'Feature',
            properties: {},
            geometry: {
              type: 'LineString',
              coordinates: route
            }
          };
          // if the route already exists on the map, reset it using setData
          if (map.getSource('route')) {
            map.getSource('route').setData(geojson);
          } else { // otherwise, make a new request
            map.addLayer({
              id: 'route',
              type: 'line',
              source: {
                type: 'geojson',
                data: {
                  type: 'Feature',
                  properties: {},
                  geometry: {
                    type: 'LineString',
                    coordinates: geojson
                  }
                }
              },
              layout: {
                'line-join': 'round',
                'line-cap': 'round'
              },
              paint: {
                'line-color': '#3887be',
                'line-width': 5,
                'line-opacity': 0.75
              }
            });
          }
          // add turn instructions here at the end
        };
        req.send();
      }

      map.on('load', function() {
        // make an initial directions request that
        // starts and ends at the same location
        getRoute(start);

        // Add starting point to the map
        map.addLayer({
          id: 'point',
          type: 'circle',
          source: {
            type: 'geojson',
            data: {
              type: 'FeatureCollection',
              features: [{
                type: 'Feature',
                properties: {},
                geometry: {
                  type: 'Point',
                  coordinates: start
                }
              }
              ]
            }
          },
          paint: {
            'circle-radius': 10,
            'circle-color': '#3887be'
          }
        });
        map.on('click', function(e) {
        var coordsObj = e.lngLat;
        canvas.style.cursor = '';
        var coords = Object.keys(coordsObj).map(function(key) {
          return coordsObj[key];
        });
        var end = {
          type: 'FeatureCollection',
          features: [{
            type: 'Feature',
            properties: {},
            geometry: {
              type: 'Point',
              coordinates: coords
            }
          }
          ]
        };
        if (map.getLayer('end')) {
          map.getSource('end').setData(end);
        } else {
          map.addLayer({
            id: 'end',
            type: 'circle',
            source: {
              type: 'geojson',
              data: {
                type: 'FeatureCollection',
                features: [{
                  type: 'Feature',
                  properties: {},
                  geometry: {
                    type: 'Point',
                    coordinates: coords
                  }
                }]
              }
            },
            paint: {
              'circle-radius': 10,
              'circle-color': '#f30'
            }
          });
        }
        getRoute(coords);
      });
      });
    </script>
  </body>
</html>

app/views/itineraries/new.html.erb
<%= render 'form', itinerary: @itinerary %>

app/views/itineraries/profile.html.erb
<div class="banner-profile" class="background-img" style="background-image: url(https://images.unsplash.com/photo-1464278500780-e60893407e29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1066&q=80);">
    <div class="heading-wrapper">
      <div class="row">
          <div class="col-sm-6 col-md-6 col-lg-4">
            <div class="info">
              <div style="font-size: 2.0rem;">
              <i class="icon far fa-user"></i>
            </div>
              <div class="right-area">
                <h5>Green</h5>
                <h6>Parrot</h6>
              </div><!-- right-area -->
            </div><!-- info -->
          </div><!-- col-sm-4 -->
          <div class="col-sm-6 col-md-6 col-lg-4">
            <div class="info">
              <div style="font-size: 2.0rem;">
              <i class="icon fas fa-qrcode"></i>
              </div>
              <div class="right-area">
                <h5>27</h5>
                <h6>Male</h6>
              </div><!-- right-area -->
            </div><!-- info -->
          </div><!-- col-sm-4 -->
          <div class="col-sm-6 col-md-6 col-lg-4">
            <div class="info">
              <div style="font-size: 2.0rem;">
              <i class="icon far fa-heart"></i>
               </div>
              <div class="right-area">
                <h5>Flying in the jungle</h5>
              </div><!-- right-area -->
            </div><!-- info -->
          </div><!-- col-sm-4 -->
      </div>
    </div>
  <div class="profile-img">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRwH86lHVa0eSuolUuJ2H7KTHqlH2YqqTn2QlcphyJr_4zJiI8E" alt="">
  </div>
</div>

app/views/itineraries/show.html.erb
<div class="modal-x" id="myModal-x">
  <div class="modal-content-x">
    <%= render 'image_carousel', itinerary: @itinerary, location: @locations %>
  </div>
</div>

<div class="show-page">
  <div class="row">
    <div class="col-5 window-view">
        <div class="itinerary-details d-flex">
          <div class='d-flex align-items-center p-0 m-0'>
            <h2 id="itinerary-name"><%= @itinerary.name %> </h2>
            <a href="#" id="review-button">
              <%= render 'review_button', itinerary: @itinerary %>
            </a>
          </div>
          <div class="d-flex align-items-end user-details-show pr-3" style="border-radius: 50%;">
          <% if @itinerary.user.photo.attached? %>
            <%= cl_image_tag @itinerary.user.photo.key, width: 50, height: 50, radius: :max, gravity: :face, :style => "border-radius: 50%"%>
          <% else %>
            <i style="font-size: 32px" class="fas fa-user-circle"></i>
          <% end %>
          </div>
        </div>

    <% if !user_signed_in? || current_user.id != @itinerary.user_id %>
      <div>
        <%= render 'itinerary_details', itinerary: @itinerary, location: @location %>
      </div>
      <% else %>
      <div class="location-form" id="ajax-location-form">
        <%= render 'location_form', itinerary: @itinerary, location: @location %>
      </div>
    <% end %>

    <%= render 'horizontal_navbar' %>

    <ul id="location-cards">
      <% @locations.each_with_index do |location, i| %>
        <li data-id="<%= location.itinerary_locations.last.drag_order %>">
          <%= link_to itinerary_location_path(@itinerary, location) do %>

            <%= render 'location', itinerary: @itinerary, location: location %>

          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-7 p-0">
    <div
    id="map" class="itinerary-locations-map the-map"
    style="width: 100%;
    height: 92vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class="review-form" id="ajax-review-form">
      <%= render 'review_form', itinerary: @itinerary, review: @review %>
    </div>
    <div id="review-show" class="review-cards">
      <h4><%= @itinerary.name.capitalize %> Reviews</h4>
      <div class="reviews-rating">
        <%= render 'review_rating', itinerary: @itinerary %>
      </div>
      <div class="review-cards-five">
        <% @reviews.last(5).reverse.each do |review| %>
          <%= render 'review', review: review %>
        <% end %>
      </div>
    </div>
  </div>
</div>