config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  patch '/profile', to: 'pages#update_profile'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_error'
  get '/422', to: 'errors#unacceptable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :itineraries do
    member do
      post "reorder", to: "locations#change_order"
    end
    resources :locations
    resources :reviews, only: [:new, :create]
    member do
      post 'clone', to: "itineraries#clone"
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Life makes more sence with DayTripper!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="logo-container">
    <%= link_to "DayTripper", root_path, class: "navbar-brand logo-font mid-grey" %>
    <i class='fas fa-map-marker-alt mid-grey'></i>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dsgxgstvy/image/upload/v1583955468/M1TmVtnnCTNwr5fbzg19oE5i.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "New Trip", new_itinerary_path, class: "dropdown-item" %>
            <%= link_to "Saved Places", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_no_itineraries_index.html.erb
<div class="row justify-content-center">
    <p class="card-text-header mt-4" style="color:#29A695"><strong>Sorry, the itinerary you are looking for doesn't exist!</strong></p>
  </div>
    <div class="row justify-content-center">
  <div class="col-md-4">
    <div class="card mt-4 card-mainpage" style="height: 25rem;">
      <img class="bd-placeholder-img card-img-top" width="100%" height="100%" src="https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_tag itineraries_path, method: :get, class: "mt-5 mb-5 search-bar-index search-bar-home" do %>

  <div class="input-group search-group mb-3">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      style: "height: 3.5rem",
      placeholder: "Search an Itinerary"
    %>
    <div class="input-group-append">
      <%= submit_tag "Search", class: "btn btn-primary search-form orange-search" %>
    </div>
  </div>
<% end %>